### ISSUE TITLE
Culture Issue on RowShare.MapEngine

### ISSUE THREAD

**Issue by didieraupest** [cubitouch/RowShareWebEngine#1]
When displaying location items, we are displaying: point.Title, point.Latitude, point.Longitude.
In French Culture, the Decimal separator is the comma, considering a decimal value as 2 different parameters.

**Comment by cubitouch** [comment]
@didieraupest can you check my last commit fixed this? :)

**Comment by didieraupest** [comment]
it works perfectly !
